spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: webshop
        auto:
          create:
            topics:
              enable: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver1:8761/eureka/,http://eurekaserver2:8762/eureka/

zipkin:
  base-url: http://localhost:9411/
sleuth:
  sampler:
    probability: 1 #100% (default = 10%)
